"""Developer seeding: one-click realistic demo leads.

A convenience for testing the console without hand-filling the questionnaire.
Gated behind WEBGEN_DEV=1 in the server, and never part of the customer flow.

Each sample is a full set of Brief answers + a Contact, so seeding produces a
normal Lead + Job — generated by whatever engine the server runs with
(WEBGEN_ENGINE=browser for real claude.ai sites; template otherwise).
"""

from __future__ import annotations

import html

SAMPLES = {
    "restaurant": {
        "label": "🍝  Restaurant — Bella Vista Trattoria",
        "answers": {
            "name": "Bella Vista Trattoria",
            "business_type": "food",
            "offerings": "A family-run Italian trattoria serving wood-fired pizza, "
                         "hand-made pasta and regional wines in a warm, rustic room.",
            "audience": ["families", "locals", "tourists"],
            "strengths": ["quality", "service", "local"],
            "area": "local",
            "years": "ten",
            "goal": ["bookings", "visit"],
            "pages": ["home", "about", "services", "gallery", "reviews", "contact"],
            "features": ["booking", "map", "gallery", "reviews"],
            "feel": "warm", "imagery": "photos", "colors": "warm", "theme": "light",
            "lang": "en",
        },
        "contact": {"name": "Mario Rossi", "email": "mario@bellavista.example",
                    "phone": "+49 30 1234567"},
    },
    "dentist": {
        "label": "🦷  Dental practice — Bright Smile Dental",
        "answers": {
            "name": "Bright Smile Dental",
            "business_type": "health",
            "offerings": "A modern family dental practice offering check-ups, "
                         "hygiene, cosmetic and emergency care with gentle, "
                         "anxiety-friendly treatment.",
            "audience": ["families", "locals", "older"],
            "strengths": ["quality", "experience", "reliability"],
            "area": "local",
            "years": "twentyfive",
            "goal": ["calls", "bookings", "inform"],
            "pages": ["home", "about", "services", "reviews", "contact"],
            "features": ["booking", "contactform", "map"],
            "feel": "professional", "imagery": "photos", "colors": "blue",
            "theme": "light", "lang": "en",
        },
        "contact": {"name": "Dr. Sarah Klein", "email": "hello@brightsmile.example",
                    "phone": "+49 89 7654321"},
    },
    "photographer": {
        "label": "📷  Photographer — Clara Nolan Photography",
        "answers": {
            "name": "Clara Nolan Photography",
            "business_type": "professional",
            "offerings": "Wedding and portrait photography with a natural, "
                         "documentary style — capturing real moments, beautifully.",
            "audience": ["young", "families"],
            "strengths": ["quality", "experience", "service"],
            "area": "region",
            "years": "few",
            "goal": ["show", "bookings"],
            "pages": ["home", "about", "gallery", "pricing", "contact"],
            "features": ["gallery", "contactform"],
            "feel": "modern", "imagery": "photos", "colors": "elegant",
            "theme": "dark", "lang": "en",
        },
        "contact": {"name": "Clara Nolan", "email": "studio@claranolan.example",
                    "phone": "+49 40 5551020"},
    },
}


def render_page(engine: str) -> str:
    """The dev seeding page: one button per sample business."""
    buttons = "".join(
        f'<form method="post" action="/api/dev/seed?kind={html.escape(k)}">'
        f'<button type="submit">{html.escape(s["label"])}</button></form>'
        for k, s in SAMPLES.items()
    )
    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>webgen · dev seeding</title>
<style>
  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; background: #f7f8fa;
         color: #111827; max-width: 640px; margin: 60px auto; padding: 0 24px; }}
  h1 {{ font-size: 24px; }}
  p {{ color: #6b7280; }}
  .engine {{ display: inline-block; background: #eef2f6; color: #334155; font-weight: 600;
             font-size: 13px; padding: 4px 12px; border-radius: 999px; }}
  form {{ margin: 12px 0; }}
  button {{ width: 100%; text-align: left; padding: 18px 20px; font-size: 16px;
           font-weight: 600; background: #fff; border: 1px solid #e2e8f0;
           border-radius: 12px; cursor: pointer; box-shadow: 0 1px 2px #0f172a08; }}
  button:hover {{ border-color: #16a34a; background: #f0fdf4; }}
  .note {{ margin-top: 28px; font-size: 13px; color: #94a3b8; }}
</style></head><body>
<h1>Seed a demo</h1>
<p>Creates a realistic lead and starts generation, then opens its console.
Generating with: <span class="engine">{html.escape(engine)}</span></p>
{buttons}
<p class="note">Dev only (WEBGEN_DEV). For real sites, run the server with
WEBGEN_ENGINE=browser and no separate worker.</p>
</body></html>"""
